# VMC Hook: Post-Placement
# Auto-generated by Vivado Methodology Checker
set vmc_reports ".runs/impl_1/vmc_hooks/vmc_reports"
file mkdir $vmc_reports


catch { report_timing_summary -max_paths 10 -file $vmc_reports/vm_timing_place.rpt }
catch { report_methodology -file $vmc_reports/vm_methodology_place.rpt }
catch { report_utilization -file $vmc_reports/vm_utilization_place.rpt }
catch { report_qor_assessment -file $vmc_reports/vm_qor_place.rpt }
catch { report_design_analysis -congestion -file $vmc_reports/vm_congestion_place.rpt }

# Signal completion
set fd [open "$vmc_reports/vm_place_done" w]
puts $fd [clock format [clock seconds]]
close $fd
