# VMC Hook: Post-Synthesis
# Auto-generated by Vivado Methodology Checker
set vmc_reports ".runs/impl_1/vmc_hooks/vmc_reports"
file mkdir $vmc_reports


catch { report_timing_summary -max_paths 10 -file $vmc_reports/vm_timing_summary.rpt }
catch { report_methodology -file $vmc_reports/vm_methodology.rpt }
catch { report_clock_interaction -file $vmc_reports/vm_clock_interaction.rpt }
catch { report_clock_networks -file $vmc_reports/vm_clock_networks.rpt }
catch { xilinx::designutils::report_failfast -file $vmc_reports/vm_failfast.rpt }
catch { report_qor_assessment -file $vmc_reports/vm_qor_assessment.rpt }
catch { report_qor_suggestions -file $vmc_reports/vm_qor_suggestions.rpt }
catch { report_utilization -file $vmc_reports/vm_utilization.rpt }
catch { report_cdc -file $vmc_reports/vm_cdc.rpt }
catch { report_design_analysis -file $vmc_reports/vm_design_analysis.rpt }
catch { report_drc -file $vmc_reports/vm_drc.rpt }

# Signal completion
set fd [open "$vmc_reports/vm_synth_done" w]
puts $fd [clock format [clock seconds]]
close $fd
