# VMC Hook: Post-Routing
# Auto-generated by Vivado Methodology Checker
set vmc_reports ".runs/impl_1/vmc_hooks/vmc_reports"
file mkdir $vmc_reports


catch { report_timing_summary -max_paths 10 -file $vmc_reports/vm_timing_route.rpt }
catch { report_methodology -file $vmc_reports/vm_methodology_route.rpt }
catch { report_utilization -file $vmc_reports/vm_utilization_route.rpt }
catch { report_clock_interaction -file $vmc_reports/vm_clock_interaction_route.rpt }
catch { report_drc -file $vmc_reports/vm_drc_route.rpt }
catch { report_power -file $vmc_reports/vm_power.rpt }

# Signal completion
set fd [open "$vmc_reports/vm_route_done" w]
puts $fd [clock format [clock seconds]]
close $fd
