"""
Hook 脚本生成器

生成 Vivado 编译各阶段结束后自动执行的 Tcl 脚本。
每个脚本运行一组 report 命令并写 DONE 标记文件。
"""

from pathlib import Path


class HookScriptGenerator:
    """Hook 脚本生成器"""

    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.reports_dir = self.output_dir / "vmc_reports"
        self.reports_dir.mkdir(exist_ok=True)

    def generate_all(self):
        self._generate_post_synth()
        self._generate_post_place()
        self._generate_post_route()

    @property
    def scripts_dir(self) -> str:
        return str(self.output_dir)

    def _header(self, stage: str) -> str:
        rdir = str(self.reports_dir).replace("\\", "/")
        return f"""# VMC Hook: Post-{stage}
# Auto-generated by Vivado Methodology Checker
set vmc_reports "{rdir}"
file mkdir $vmc_reports

"""

    def _done_marker(self, stage: str) -> str:
        return f"""
# Signal completion
set fd [open "$vmc_reports/vm_{stage}_done" w]
puts $fd [clock format [clock seconds]]
close $fd
"""

    def _generate_post_synth(self):
        script = self._header("Synthesis") + """
catch { report_timing_summary -max_paths 10 -file $vmc_reports/vm_timing_summary.rpt }
catch { report_methodology -file $vmc_reports/vm_methodology.rpt }
catch { report_clock_interaction -file $vmc_reports/vm_clock_interaction.rpt }
catch { report_clock_networks -file $vmc_reports/vm_clock_networks.rpt }
catch { report_failfast -file $vmc_reports/vm_failfast.rpt }
catch { report_qor_assessment -file $vmc_reports/vm_qor_assessment.rpt }
catch { report_qor_suggestions -file $vmc_reports/vm_qor_suggestions.rpt }
catch { report_utilization -file $vmc_reports/vm_utilization.rpt }
catch { report_cdc -file $vmc_reports/vm_cdc.rpt }
catch { report_design_analysis -file $vmc_reports/vm_design_analysis.rpt }
catch { report_drc -file $vmc_reports/vm_drc.rpt }
""" + self._done_marker("synth")

        (self.output_dir / "vm_post_synth.tcl").write_text(script, encoding="utf-8")

    def _generate_post_place(self):
        script = self._header("Placement") + """
catch { report_timing_summary -max_paths 10 -file $vmc_reports/vm_timing_place.rpt }
catch { report_methodology -file $vmc_reports/vm_methodology_place.rpt }
catch { report_utilization -file $vmc_reports/vm_utilization_place.rpt }
catch { report_qor_assessment -file $vmc_reports/vm_qor_place.rpt }
catch { report_design_analysis -congestion -file $vmc_reports/vm_congestion_place.rpt }
""" + self._done_marker("place")

        (self.output_dir / "vm_post_place.tcl").write_text(script, encoding="utf-8")

    def _generate_post_route(self):
        script = self._header("Routing") + """
catch { report_timing_summary -max_paths 10 -file $vmc_reports/vm_timing_route.rpt }
catch { report_methodology -file $vmc_reports/vm_methodology_route.rpt }
catch { report_utilization -file $vmc_reports/vm_utilization_route.rpt }
catch { report_clock_interaction -file $vmc_reports/vm_clock_interaction_route.rpt }
catch { report_drc -file $vmc_reports/vm_drc_route.rpt }
catch { report_power -file $vmc_reports/vm_power.rpt }
""" + self._done_marker("route")

        (self.output_dir / "vm_post_route.tcl").write_text(script, encoding="utf-8")
